import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../src/engine.js';
import * as W from '../src/world.js';
import {JOBS,SKILLS,EVOLUTIONS,BOONS,WEAPONS,BOSS_SPECS} from '../src/data.js';
const copy=structuredClone;
function arena(jobs=['knight','mage','shrine'],seed='TACTICS'){
 const r=E.createRun(jobs,seed);r.dungeon.packs=[];E.startBattle(r);for(const e of r.battle.enemies){e.hp=e.maxHp=50000;e.atk=e.mag=0;e.intent=['attack'];e.plannedIntent='attack';e.def=0;}
 for(const h of r.party)h.weapon.effect='none';return r;
}
const foe=r=>r.battle.enemies.find(e=>e.hp>0);
const use=(r,h,id,target)=>E.act(r,id,target||foe(r)?.id,r.party[h].id);
function world(){
 const r=E.createRun(['knight','ninja','chrono'],'WORLD');const d=r.dungeon;
 d.size=13;d.tiles=Array.from({length:13},(_,y)=>Array.from({length:13},(_,x)=>x===0||y===0||x===12||y===12?1:0));d.visited=d.tiles.map(a=>a.map(()=>true));d.zones=d.tiles.map(a=>a.map(()=>0));d.events={};d.landmarks=[];d.packs=[];d.elapsed=0;r.x=5;r.y=5;r.dir=1;return r;
}
function pack(r,id,x,y,kind='normal',troop=['slime']){
 const p={id,name:id,x,y,home:{x,y},troop,kind,route:[{x,y},{x:x+1,y}],routeIndex:0,alert:0,alertUntil:0,alarmTarget:null,cooldown:0,sleepUntil:0,sleepResistUntil:0,lure:null,defeated:false,engaged:false};r.dungeon.packs.push(p);return p;
}
function fixtureBoss(floor=1,jobs=['knight','mage','shrine']){const r=arena(jobs,'BOSS'+floor);r.phase='explore';r.battle=null;r.floor=floor;E.startBattle(r,floor===5?'boss':'guardian');for(const h of r.party)h.hp=h.maxHp=5000;for(const e of r.battle.enemies)e.atk=e.mag=5;return r;}
function highArts(r){for(const h of r.party)h.skills=[...JOBS[h.job].skills,...JOBS[h.job].advanced];}
function guardAll(r){for(const h of r.party)if(h.hp>0)E.act(r,'guard',null,h.id);}
function omen(r,counter){const b=foe(r);b.boss.pending={id:'fixture',name:'试炼',counter,dueRound:r.battle.round,bornRound:r.battle.round,hits:0,required:4,addIds:[],source:'test'};if(['dispel','seal'].includes(counter))b.status.veil={turns:99,power:1};return b;}

test('no MP or speed initiative: party starts in preparation without any enemy actions',()=>{const r=arena();for(const h of r.party){assert.equal(h.mp,undefined);assert.equal(h.maxMp,undefined);assert.equal(h.spd,undefined);}assert.equal(r.battle.stage,'prepare');assert.equal(r.battle.round,1);assert.deepEqual(r.battle.queue,[]);assert.ok(r.battle.enemies.every(e=>e.intentIndex===0));});
test('many skills across all characters are instantaneous, independent, and do not move the world',()=>{const r=arena(),clock=r.dungeon.elapsed;assert.ok(use(r,0,'cleave').ok);assert.ok(use(r,0,'aegis').ok);assert.ok(use(r,1,'fire').ok);assert.ok(use(r,1,'frost').ok);assert.ok(use(r,2,'cleanse').ok);assert.equal(r.battle.round,1);assert.equal(r.dungeon.elapsed,clock);assert.ok(r.battle.enemies.every(e=>e.intentIndex===0));assert.equal(r.party[1].cooldowns.fire,3);assert.equal(r.party[1].cooldowns.frost,3);});
test('CD3 used on R1 is next usable R4; all team attacks tick it exactly once',()=>{const r=arena();use(r,1,'fire');for(let n=2;n>=0;n--){E.attackRound(r);assert.equal(r.party[1].cooldowns.fire,n);}assert.equal(r.battle.round,4);assert.ok(use(r,1,'fire').ok);assert.equal(r.party[1].cooldowns.fire,3);});
test('selecting characters and guard toggling do not tick cooldowns or world time',()=>{const r=arena();use(r,1,'fire');const rng=r.rng;for(let i=0;i<4;i++){assert.ok(E.selectHero(r,r.party[i%3].id));assert.ok(E.act(r,'guard').ok);}assert.equal(r.rng,rng);assert.equal(r.battle.round,1);assert.equal(r.dungeon.elapsed,0);assert.equal(r.party[1].cooldowns.fire,3);});
test('party attacks always precede enemy side regardless of legacy speed values',()=>{const r=arena();r.party[0].spd=-100;foe(r).spd=1e9;E.attackRound(r);const frames=r.frames.filter(f=>f.side==='party'||f.side==='enemy'),firstEnemy=frames.findIndex(f=>f.side==='enemy');assert.equal(firstEnemy,3);assert.ok(frames.slice(firstEnemy).every(f=>f.side==='enemy'));assert.equal(r.battle.round,2);assert.equal(r.dungeon.elapsed,1);});
test('guard skips only that member normal attack and protects during enemy phase',()=>{const a=arena(),b=copy(a);for(const r of [a,b]){foe(r).atk=40;foe(r).targetId=r.party[0].id;}E.act(b,'guard',null,b.party[0].id);const ah=a.party[0].hp,bh=b.party[0].hp;E.attackRound(a);E.attackRound(b);assert.ok(bh-b.party[0].hp<(ah-a.party[0].hp)*.6);assert.equal(b.party[0].guard,false);assert.ok(b.frames.find(f=>f.actorId===b.party[0].id&&f.label==='防御'));});
test('invalid cooldown, ownership, target, and actor commands cannot spend resources or RNG',()=>{const r=arena();use(r,1,'fire');for(const cmd of [()=>use(r,1,'fire'),()=>use(r,0,'fire'),()=>use(r,1,'frost','nope'),()=>E.act(r,'frost',foe(r).id,'nope'),()=>E.attackRound(r,'nope')]){const before=E.serializeRun(r);assert.equal(cmd().ok,false);assert.equal(E.serializeRun(r),before);}});
test('finite battle items are free commands, not enemy actions or cooldown ticks',()=>{const r=arena();r.party[0].hp=1;use(r,1,'fire');const round=r.battle.round,tick=r.dungeon.elapsed,rng=r.rng;assert.ok(E.act(r,'tonic',r.party[0].id).ok);assert.ok(E.act(r,'ether',r.party[1].id).ok);assert.equal(r.supplies.tonic,2);assert.equal(r.supplies.ether,1);assert.equal(r.battle.round,round);assert.equal(r.dungeon.elapsed,tick);assert.equal(r.rng,rng);assert.equal(r.party[1].cooldowns.fire,2);});
test('map healing consumes one item but never advances a pack or a step',()=>{const r=world();pack(r,'patrol',7,5);r.party[0].hp=1;const before=copy(r.dungeon);assert.ok(E.useSupply(r,'tonic',r.party[0].id).ok);assert.deepEqual(r.dungeon,before);assert.equal(r.steps,0);});
test('same-turn haste and time-sand cannot enable repeated infinitely free casts',()=>{const r=arena(['mage','chrono','reaver']);use(r,0,'fire');r.supplies.ether=30;for(let i=0;i<15;i++)E.act(r,'ether',r.party[0].id);assert.equal(r.party[0].cooldowns.fire,1);assert.equal(use(r,0,'fire').ok,false);E.act(r,'haste',r.party[1].id,r.party[1].id);for(let i=0;i<5;i++)E.act(r,'ether',r.party[1].id);assert.equal(r.party[1].cooldowns.haste,5);use(r,2,'bloodpact');for(let i=0;i<5;i++)E.act(r,'ether',r.party[2].id);assert.equal(r.party[2].cooldowns.bloodpact,5);});
test('healing weapon procs happen once per round, not once per free skill/item/toggle',()=>{const r=arena();r.party[0].weapon.effect='chorus';r.party[2].hp=10;for(let i=0;i<6;i++)E.act(r,'guard',null,r.party[0].id);assert.equal(r.party[2].hp,10);E.attackRound(r);assert.ok(r.party[2].hp<=18);});
test('DoT and status duration tick once per complete round, not each skill',()=>{const r=arena();const h=r.party[0];h.status.poison={power:5,turns:3};const before=h.hp;use(r,1,'fire');use(r,1,'frost');assert.equal(h.hp,before);assert.equal(h.status.poison.turns,3);E.attackRound(r);assert.ok(h.hp<=before-5);assert.equal(h.status.poison.turns,2);});
test('dead targets are retargeted during the team normal attack phase',()=>{const r=arena();const e=foe(r);e.hp=1;const second=copy(e);second.id='another';second.hp=second.maxHp=10000;r.battle.enemies=[e,second];E.attackRound(r,e.id);assert.equal(e.hp,0);assert.ok(second.hp<10000);});
test('skill-only victory does not advance a fake round or patrol tick',()=>{const r=arena();r.battle.enemies=[foe(r)];foe(r).hp=1;assert.ok(use(r,0,'cleave').ok);assert.equal(r.phase,'reward');assert.equal(r.dungeon.elapsed,0);});
test('attack killing the last enemy advances world once and can admit an incoming pack',()=>{const r=world(),p=pack(r,'elite-incoming',6,5,'elite');E.startBattle(r);for(const e of r.battle.enemies)e.hp=1;for(const h of r.party)h.atk=10000;E.attackRound(r);assert.equal(r.dungeon.elapsed,1);assert.equal(r.phase,'battle');assert.ok(p.engaged);assert.ok(p.members.every(e=>e.intentIndex===0&&e.readyRound===2));});

test('fixed patrol positions are unaffected by party proximity and consume no RNG',()=>{const a=world();pack(a,'p',7,5);const b=copy(a);b.x=10;b.y=10;const rng=a.rng;for(let i=0;i<8;i++){W.stepPacks(a);W.stepPacks(b);assert.deepEqual([a.dungeon.packs[0].x,a.dungeon.packs[0].y],[b.dungeon.packs[0].x,b.dungeon.packs[0].y]);}assert.equal(a.rng,rng);});
test('generated patrol cycles are fixed, walkable and cardinal including wrap-around',()=>{for(let seed=0;seed<50;seed++){const r=E.createRun(['knight'],'PATROL'+seed);for(const p of r.dungeon.packs){assert.deepEqual(p.route,W.patrolRoute(r.dungeon,p.home.x,p.home.y));for(let i=0;i<p.route.length;i++){const a=p.route[i],b=p.route[(i+1)%p.route.length];assert.ok(W.isFloor(r.dungeon,a.x,a.y));assert.ok(Math.abs(a.x-b.x)+Math.abs(a.y-b.y)<=1);}}}});
test('normal packs keep patrol routes during combat instead of automatically homing in',()=>{const r=world(),p=pack(r,'p',7,5);E.startBattle(r);for(const e of r.battle.enemies){e.hp=e.maxHp=10000;e.atk=e.mag=0;}E.attackRound(r);assert.equal(p.x,8);assert.equal(p.alertUntil,0);});
test('elite tracks party beyond the former eight-tile hearing range and ignores lure',()=>{const r=world(),p=pack(r,'elite',10,10,'elite');W.stepPacks(r);assert.equal(Math.abs(p.x-r.x)+Math.abs(p.y-r.y),9);assert.equal(W.packMode(r,p),'elite');assert.equal(W.useFieldTool(r,'lure').ok,false);});
test('alarm only targets ordinary packs within path-eight and does not itself advance time',()=>{const r=world(),near=pack(r,'near',7,5),far=pack(r,'far',10,10),elite=pack(r,'elite',8,8,'elite');const rng=r.rng;assert.deepEqual(W.raiseAlarm(r),{blocked:false,count:1});assert.equal(near.alertUntil,6);assert.equal(far.alertUntil,0);assert.equal(elite.alertUntil,0);assert.equal(r.dungeon.elapsed,0);assert.equal(r.rng,rng);W.stepPacks(r);assert.equal(near.x,6);});
for(const mode of ['success','sealed','killed','hushed'])test(`alarm enemy ${mode}: aggro requires its successful enemy-side action`,()=>{const r=world(),watch=pack(r,'watch',7,5),battlePack=pack(r,'caller',5,5,'normal',['caller','slime']);if(mode==='hushed')assert.ok(W.useFieldTool(r,'hush').ok);E.startBattle(r,'normal',null,[battlePack]);const caller=r.battle.enemies.find(e=>e.type==='caller');for(const e of r.battle.enemies){e.hp=e.maxHp=10000;e.atk=e.mag=0;}if(mode==='sealed')caller.status.headbind={turns:2,power:1};if(mode==='killed')caller.hp=0;E.attackRound(r);assert.equal(watch.alertUntil>0,mode==='success');assert.equal(watch.x,mode==='success'?6:8);});
test('head seal consumes the alarm intent instead of saving it until the seal expires',()=>{const r=world(),p=pack(r,'alarm',5,5,'normal',['caller']);pack(r,'p',7,5);E.startBattle(r,'normal',null,[p]);const e=foe(r);e.hp=e.maxHp=10000;e.status.headbind={turns:2};E.attackRound(r);assert.equal(e.intentIndex,1);assert.equal(E.intentOf(e),'bound');E.attackRound(r);assert.equal(e.intentIndex,2);assert.equal(r.dungeon.packs[1].alertUntil,0);});
test('lure attracts toward its placed tile, not the moving player, then resumes patrol',()=>{const r=world(),p=pack(r,'p',7,5);assert.ok(W.useFieldTool(r,'lure').ok);assert.equal(r.dungeon.elapsed,0);r.x=5;r.y=7;W.stepPacks(r);assert.deepEqual([p.x,p.y],[6,5]);W.stepPacks(r);assert.deepEqual([p.x,p.y],[5,5]);for(let i=0;i<4;i++)W.stepPacks(r);assert.equal(p.x,6);assert.equal(W.packMode(r,p),'return');});
for(const kind of ['normal','elite'])test(`${kind} sleep stops exactly its permitted steps and has reapplication resistance`,()=>{const r=world(),p=pack(r,'p',7,5,kind);assert.ok(W.useFieldTool(r,'sleep',p.id).ok);assert.equal(r.dungeon.elapsed,0);const count=kind==='elite'?1:3;for(let i=0;i<count;i++){W.stepPacks(r);assert.equal(p.x,7);}W.stepPacks(r);assert.notEqual(p.x,7);r.fieldSupplies.sleep=5;const before=E.serializeRun(r);assert.equal(W.useFieldTool(r,'sleep',p.id).ok,false);assert.equal(E.serializeRun(r),before);});
test('field tools reject battle, missing target, hidden target, too-distant target and repeat without spending',()=>{const r=world(),p=pack(r,'p',10,10);for(const id of ['sleep','unknown']){const before=E.serializeRun(r);assert.equal(W.useFieldTool(r,id,p.id).ok,false);assert.equal(E.serializeRun(r),before);}p.x=6;p.y=5;r.dungeon.visited[5][6]=false;assert.equal(W.useFieldTool(r,'sleep',p.id).ok,false);E.startBattle(r);const before=E.serializeRun(r);assert.equal(W.useFieldTool(r,'hush').ok,false);assert.equal(E.serializeRun(r),before);});
test('full enemy formations wait at six-unit capacity without being lost',()=>{const r=world(),p=pack(r,'incoming',6,5,'elite',['slime','moth']);E.startBattle(r);const base=foe(r);r.battle.enemies=Array.from({length:6},(_,i)=>({...copy(base),id:'e'+i,hp:50000,maxHp:50000,atk:0,mag:0}));E.attackRound(r);assert.equal(p.engaged,false);assert.equal(p.x,5);assert.equal(r.battle.enemies.length,6);});
test('arrival round reinforcements cannot act before the next whole attack',()=>{const r=world(),p=pack(r,'incoming',6,5,'elite');E.startBattle(r);for(const e of r.battle.enemies){e.hp=e.maxHp=50000;e.atk=e.mag=0;}E.attackRound(r);const joined=p.members[0];assert.equal(joined.intentIndex,0);assert.equal(joined.readyRound,2);E.attackRound(r);assert.equal(joined.intentIndex,1);});

for(let floor=1;floor<=5;floor++)test(`B${floor} HP triggers still give a full next preparation window`,()=>{const r=fixtureBoss(floor);const e=foe(r);r.party[0].atk=100000;use(r,0,'cleave');assert.equal(e.boss.hpTriggered.length,1);assert.equal(e.boss.pending,null);assert.equal(r.battle.round,1);guardAll(r);E.attackRound(r);assert.ok(e.boss.pending);assert.equal(e.boss.pending.bornRound,2);assert.equal(e.boss.pending.dueRound,2);assert.equal(r.battle.stage,'prepare');});
for(const method of ['dispel','seal','hits','adds'])test(`Boss ${method} cancellation works after multiple free preparation commands`,()=>{const r=fixtureBoss(1,['knight','ninja','chrono']);highArts(r);const e=omen(r,method);if(method==='dispel')assert.ok(use(r,2,'unweave',e.id).ok);if(method==='seal')assert.ok(use(r,1,'seal',e.id).ok);if(method==='hits')e.boss.pending.hits=e.boss.pending.required;if(method==='adds')e.boss.pending.addIds=[];guardAll(r);E.attackRound(r);assert.ok(r.log.some(l=>l.text.includes('预兆解除')));assert.equal(e.boss.pending,null);});
test('time delay preserves a pending omen and cannot extend the same omen twice',()=>{const r=fixtureBoss(1,['knight','chrono']);highArts(r);const e=omen(r,'guard');assert.ok(use(r,1,'delay',e.id).ok);assert.equal(e.boss.pending.dueRound,2);r.party[1].cooldowns.delay=0;const before=E.serializeRun(r);assert.equal(use(r,1,'delay',e.id).ok,false);assert.equal(E.serializeRun(r),before);});
test('boss omen is an enemy action, not an extra normal attack plus an unannounced hit',()=>{const r=fixtureBoss();const e=omen(r,'guard');guardAll(r);E.attackRound(r);assert.equal(e.intentIndex,0);assert.equal(r.frames.filter(f=>f.style==='omen').length,1);assert.ok(r.frames.filter(f=>f.actorId===e.id).some(f=>f.label==='预兆蓄势'));});
test('unresolved boss bloodlines cannot be bypassed by stacked free skills',()=>{const r=fixtureBoss(5,['knight','mage','reaver']);highArts(r);for(const h of r.party)h.atk=h.mag=100000;for(let i=0;i<r.party.length;i++)for(const id of r.party[i].skills)use(r,i,id,foe(r)?.id);assert.equal(r.phase,'battle');assert.ok(foe(r).hp>=1);assert.equal(foe(r).boss.hpResolved.length,0);});
test('real final boss can reach victory only after all pending HP phases resolve',()=>{const r=fixtureBoss(5,['knight','mage','shrine']);for(const h of r.party)h.atk=h.mag=100000;let n=0;while(r.phase==='battle'&&n++<20){E.attackRound(r);}assert.equal(r.ending,'victory');assert.ok(n>=BOSS_SPECS[4].hp.length);});
test('enemy buff, attack, target damage and alarm emit separate presentation frames',()=>{const r=world(),p=pack(r,'p',5,5,'normal',['caller','moth','slime']);E.startBattle(r,'normal',null,[p]);for(const e of r.battle.enemies)e.hp=e.maxHp=5000;E.attackRound(r);assert.ok(r.frames.some(f=>f.style==='alarm'));assert.ok(r.frames.some(f=>f.side==='enemy'&&f.fx.some(x=>x.type==='damage')));assert.ok(r.frames.every(f=>Array.isArray(f.party)&&Array.isArray(f.fx)));const serialized=E.serializeRun(r);assert.ok(!serialized.includes('"frames"'));});
test('save round-trip retains cooldowns, alarm route identities and deterministic next round',()=>{const r=world(),p=pack(r,'p',5,5,'normal',['caller']);pack(r,'near',8,5);E.startBattle(r,'normal',null,[p]);foe(r).hp=foe(r).maxHp=10000;use(r,0,'cleave');E.attackRound(r);const b=E.restoreRun(E.serializeRun(r));assert.equal(b.dungeon.packs[0].members[0],b.battle.enemies[0]);E.attackRound(r);E.attackRound(b);assert.equal(E.serializeRun(r),E.serializeRun(b));});
test('malformed cooldowns, route and old-version saves fail closed',()=>{for(const mutate of [r=>r.version=2,r=>r.party[0].cooldowns.cleave=-1,r=>r.dungeon.packs[0].route=[{x:0,y:0}],r=>r.fieldSupplies.hush=-1]){const r=E.createRun(['knight'],'BAD');mutate(r);assert.throws(()=>E.restoreRun(JSON.stringify(r)));}});
for(const [job,j]of Object.entries(JOBS))test(`${job}: learned skills/qualitative evolution remain run-local and bounded`,()=>{const r=E.createRun([job],'GROW');r.floor=3;const h=r.party[0];for(const id of j.advanced){r.phase='reward';r.rewards=[{type:'learn',heroId:h.id,skillId:id}];assert.ok(E.takeReward(r,0).ok);assert.ok(h.skills.includes(id));}const id=j.skills[0];h.ranks[id]=1;r.phase='reward';r.rewards=[{type:'evolve',heroId:h.id,skillId:id}];assert.ok(E.takeReward(r,0).ok);assert.ok(h.evolutions[id]);const fresh=E.createRun([job],'GROW');assert.deepEqual(fresh.party[0].skills,j.skills);assert.deepEqual(fresh.party[0].evolutions,{});});
for(const [id,evo]of Object.entries(EVOLUTIONS))test(`${id}: effective awakening contains its actual rule patch`,()=>{const j=Object.keys(JOBS).find(j=>JOBS[j].skills.includes(id));const r=E.createRun([j],'EVO'),h=r.party[0];h.evolutions[id]=true;const result=E.effectiveSkill(h,id);for(const [k,v]of Object.entries(evo.patch))assert.deepEqual(result[k],v);assert.equal(SKILLS[id].desc.includes('觉醒：'),false);});
test('cooldown discounts have a floor; ranking and weapon changes never create free spam',()=>{const r=arena();for(const h of r.party){h.weapon.effect='economy';for(const id of h.skills){h.ranks[id]=2;assert.ok(E.skillCooldown(h,id)>=2);}}});

test('escaping and re-entering the same pack preserves cooldowns and one-shot survival use',()=>{const r=world(),p=pack(r,'p',5,5);E.startBattle(r,'normal',null,[p]);foe(r).hp=foe(r).maxHp=50000;use(r,0,'cleave');r.party[0].phoenixUsed=true;r.party[0].laststandUsed=true;r.battle.escapeAttempts=1;assert.ok(E.act(r,'escape').ok);assert.equal(r.phase,'explore');E.startBattle(r,'normal',null,[p]);assert.equal(r.party[0].cooldowns.cleave,3);assert.equal(r.party[0].phoenixUsed,true);assert.equal(r.party[0].laststandUsed,true);assert.equal(use(r,0,'cleave').ok,false);});
test('head binding suppresses skills but does not prohibit a potion during preparation',()=>{const r=arena();r.party[2].status.headbind={turns:2};r.party[2].hp=1;assert.equal(E.act(r,'mend',r.party[2].id,r.party[2].id).ok,false);assert.ok(E.act(r,'tonic',r.party[2].id,r.party[2].id).ok);assert.equal(r.battle.round,1);});
test('two enemy support actions and a marked hunter cooperate within one enemy side',()=>{const r=world(),p=pack(r,'p',5,5,'normal',['wisp','moth']);E.startBattle(r,'normal',null,[p]);for(const e of r.battle.enemies)e.hp=e.maxHp=10000;const [mark,hunter]=r.battle.enemies;mark.plannedIntent='mark';hunter.plannedIntent='hunt';mark.targetId=r.party[2].id;hunter.targetId=r.party[0].id;E.attackRound(r);assert.ok(r.party[2].status.marked);assert.ok(r.frames.some(f=>f.actorId===hunter.id&&f.fx.some(x=>x.id===r.party[2].id&&x.type==='damage')));});
test('single-turn protection expires after the enemy phase, not after another free ally skill',()=>{const r=arena();use(r,0,'aegis');use(r,1,'fire');assert.ok(r.party.every(p=>p.status.protect));E.attackRound(r);assert.ok(r.party.every(p=>!p.status.protect));});
test('an enemy-created mark lasts into the next preparation and next enemy-side hunt',()=>{const r=arena();const e=foe(r);e.plannedIntent='mark';e.intent=['mark','hunt'];e.targetId=r.party[0].id;E.attackRound(r);assert.equal(r.party[0].status.marked.turns,3);E.attackRound(r);assert.equal(r.party[0].status.marked.turns,2);});
test('awakened overheal, dual-hit reaver, group haste and seal affect actual state',()=>{const r=arena(['shrine','reaver','chrono']);highArts(r);for(const h of r.party)for(const id of h.skills)if(EVOLUTIONS[id])h.evolutions[id]=true;assert.ok(use(r,0,'mend',r.party[0].id).ok);assert.ok(r.party[0].barrier>0);assert.ok(use(r,1,'rend').ok);assert.equal(r.fx.filter(x=>x.type==='damage').length,2);for(const h of r.party)h.cooldowns[h.skills[0]]=2;assert.ok(use(r,2,'haste').ok);assert.ok(r.party.every(h=>h.status.haste));const n=arena(['ninja']);n.party[0].evolutions.seal=true;assert.ok(use(n,0,'seal').ok);assert.ok(n.battle.enemies.every(e=>e.status.headbind));});
test('focus and echo add real hits, then consume their buffs once',()=>{const r=arena(['mage','chrono']);highArts(r);assert.ok(use(r,0,'focuscast').ok);assert.ok(use(r,1,'echoTime',r.party[0].id).ok);assert.ok(use(r,0,'fire').ok);assert.equal(r.fx.filter(x=>x.type==='damage').length,3);assert.equal(r.party[0].status.focus,undefined);assert.equal(r.party[0].status.echo,undefined);});
test('invalid repeated item or empty dispel does not consume charges or start a cooldown',()=>{const r=arena(['chrono']);highArts(r);r.supplies.tonic=0;for(const id of ['tonic','unweave','salt']){const before=E.serializeRun(r);assert.equal(use(r,0,id,r.party[0].id).ok,false);assert.equal(E.serializeRun(r),before);}});
